### PR TITLE
Syntax-highlight code blocks

### PR DESCRIPTION
**Pull request by felixfbecker**
This will make our docs a lot more readable.

### CODE REVIEW

**Comment by felixfbecker** [comment]
I tried a lot of things and this was the only way to get it working, see https://github.com/Depado/bfchroma/issues/4
I generally don't set `GO111MODULE` because I read it is enabled by default when operating outside of `GOPATH`, which I do.
How do I enable `GO111MODULE` when running `goimports`? I never run that manually, I just use VS Code. Auto imports have been broken for a while for me, I always add imports manually.
If you find a better way to import feel free to change though, this was the only way I could get it to work

**Comment by sqs** [comment]
That’s fine

**Comment by Depado** [comment]
Why am I so thrilled that sourcegraph decided to use one of my libs, even if it's just for their docs ? :smile: 
The gomodule thing is pretty mind-blowing, especially when using blackfriday, unfortunately. When it will be adopted by more people I'll switch the usage avec bfchroma to only use modules, thus switching to the `/v2` blackfriday import path. Sorry if that's inconvenient for now.

Cheers :+1:

**Comment by sqs** [comment]
Thanks, @depado, for the awesome lib!

**Pull request merged**
