### PR TITLE
refactor: migrate to goldmark

### PR DESCRIPTION
**Pull request by unknwon**
Migrate our Markdown render from [blackfriday](https://github.com/russross/blackfriday) to the state-of-the-art [goldmark](https://github.com/yuin/goldmark), which gives us more familiarity with GitHub GFM.

This refactoring should remain feature parity.

## Test plan

<details>
<summary>Inline anchor</summary>

CleanShot 2023-02-09 at 17 07 37@2x

</details>

<details>
<summary>TOC and Markdown function (jsonschema)</summary>

CleanShot 2023-02-09 at 17 08 16@2x

</details>

<details>
<summary>Search</summary>

CleanShot 2023-02-09 at 17 10 06@2x

</details>

<details>
<summary>Warning and note</summary>

CleanShot 2023-02-09 at 17 10 47@2x

</details>

### CODE REVIEW

**Review by sqs — APPROVED** [review]
Awesome, this is so great! Can you try it out on docs.sourcegraph.com locally and see if  there are any regressions? (I mean, not 100% strict inspection, but just doing a quick check.)

**Comment by unknwon** [comment]
> Can you try it out on docs.sourcegraph.com locally and see if there are any regressions? (I mean, not 100% strict inspection, but just doing a quick check.)

This is what I've been testing with locally, I'll post some notable elements in PR description 😁

**Review by mrnugget — APPROVED** [review]
Have to admit: didn't review all of it and also not super carefully. If you tested this with our existing docs and the most complex pages look fine (something like this: https://docs.sourcegraph.com/batch_changes/how-tos/configuring_credentials) - let's do this!

**Comment by unknwon** [comment]
CleanShot 2023-02-09 at 17 24 39@2x

**Comment by unknwon** [comment]
Given we [don't publish new versions automatically](https://github.com/sourcegraph/docsite#release-a-new-version) by just merging to `main`, I think it is super low-risk to merge this and iterate from here!

**Review by sashaostrikov — APPROVED** [review]
NICE!

**Pull request merged**
